import { StyleSheet } from "react-native";

import { stitchPalette } from "@/shared/theme";

const styles = StyleSheet.create({
  heroCard: {
    backgroundColor: stitchPalette.surface,
    borderRadius: 24,
    padding: 14,
    borderWidth: 1,
    borderColor: stitchPalette.borderStrong,
    gap: 8,
  },
  heroKicker: {
    color: stitchPalette.accentSoft,
    fontSize: 11,
    letterSpacing: 3,
    fontWeight: "800",
  },
  heroTitle: {
    color: stitchPalette.text,
    fontSize: 26,
    fontWeight: "900",
  },
  heroSubtitle: {
    color: stitchPalette.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  summaryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 2,
    gap: 6,
  },
  summaryChip: {
    minWidth: 78,
    flexGrow: 1,
    backgroundColor: stitchPalette.surfaceAlt,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: stitchPalette.borderSoft,
    paddingVertical: 9,
    paddingHorizontal: 12,
  },
  summaryLabel: {
    color: stitchPalette.textSubtle,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  summaryValue: {
    marginTop: 4,
    color: stitchPalette.text,
    fontSize: 20,
    fontWeight: "900",
  },
  filterRow: {
    flexDirection: "row",
    paddingVertical: 6,
    flexWrap: "wrap",
    gap: 7,
  },
  filterChip: {
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderRadius: 16,
    backgroundColor: stitchPalette.surface,
    borderWidth: 1,
    borderColor: "rgba(246, 192, 106, 0.18)",
  },
  filterChipActive: {
    backgroundColor: "#f6c06a",
  },
  filterText: {
    color: "#cbd5e1",
    fontSize: 13,
    fontWeight: "700",
  },
  filterTextActive: {
    color: "#111827",
  },
  listHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  listHeaderTitle: {
    color: "#f8fafc",
    fontSize: 16,
    fontWeight: "800",
  },
  listHeaderSub: {
    color: "#94a3b8",
    fontSize: 12,
    fontWeight: "700",
  },
  card: {
    backgroundColor: "#101b31",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: stitchPalette.borderStrong,
    padding: 12,
  },
  cardTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  cardCode: {
    color: stitchPalette.text,
    fontSize: 18,
    fontWeight: "900",
  },
  cardTime: {
    marginTop: 4,
    color: stitchPalette.textMuted,
    fontSize: 13,
  },
  statusPill: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignSelf: "flex-start",
  },
  statusText: {
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.6,
    color: stitchPalette.ink,
  },
  statusConfirmed: {
    backgroundColor: "rgba(34,197,94,0.18)",
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.5)",
    shadowColor: "rgba(34,197,94,0.16)",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
    elevation: 6,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  statusPending: {
    backgroundColor: "rgba(245,158,11,0.18)",
    borderWidth: 1,
    borderColor: "rgba(245,158,11,0.5)",
    shadowColor: "rgba(245,158,11,0.14)",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
    elevation: 5,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  statusWaiting: {
    backgroundColor: "rgba(121,168,255,0.12)",
    borderWidth: 1,
    borderColor: "rgba(121,168,255,0.26)",
    shadowColor: "rgba(121,168,255,0.12)",
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 5,
  },
  statusCancelled: {
    backgroundColor: "rgba(239,124,84,0.10)",
    borderWidth: 1,
    borderColor: "rgba(239,124,84,0.24)",
    shadowColor: "rgba(239,124,84,0.10)",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 10,
    elevation: 4,
  },
  metaBlock: {
    paddingTop: 2,
  },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  metaLabel: {
    color: stitchPalette.textSubtle,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  metaValue: {
    color: stitchPalette.textSoft,
    fontSize: 13,
    fontWeight: "600",
    flexShrink: 1,
    textAlign: "right",
  },
  actionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  primaryAction: {
    flex: 1,
    backgroundColor: stitchPalette.accent,
    borderRadius: 18,
    paddingVertical: 13,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  primaryActionText: {
    color: stitchPalette.ink,
    fontSize: 13,
    fontWeight: "900",
  },
  secondaryAction: {
    paddingHorizontal: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.14)",
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryActionText: {
    color: stitchPalette.text,
    fontSize: 13,
    fontWeight: "800",
  },
  infoCard: {
    marginTop: 14,
    backgroundColor: stitchPalette.surfaceAlt,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: stitchPalette.borderSoft,
    padding: 14,
    gap: 8,
  },
  infoTitle: {
    color: stitchPalette.text,
    fontSize: 15,
    fontWeight: "800",
  },
  infoBody: {
    color: stitchPalette.textMuted,
    fontSize: 13,
    lineHeight: 20,
  },
  cardTopRowCentered: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 8,
  },
  timeBlock: {
    alignItems: "flex-start",
  },
  cardTimeLarge: {
    color: "#f8fafc",
    fontSize: 25,
    fontWeight: "900",
  },
  cardLocation: {
    color: "#94f2c9",
    fontSize: 13,
    marginTop: 4,
    fontWeight: "800",
  },
  metaBlockCompact: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 6,
    paddingBottom: 10,
  },
  cardCodeCompact: {
    color: "#f6f7fb",
    fontSize: 14,
    fontWeight: "900",
  },
  metaValueCompact: {
    color: "#cbd5e1",
    fontSize: 13,
    fontWeight: "700",
  },
  primaryActionLarge: {
    flex: 1,
    backgroundColor: "#f59e0b",
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryActionTextLarge: {
    color: "#071122",
    fontSize: 16,
    fontWeight: "900",
  },
  pageContainer: {
    alignSelf: "center",
    width: "100%",
    maxWidth: 680,
    paddingHorizontal: 10,
  },
  listContainer: {
    gap: 10,
    marginTop: 10,
  },
  cardWide: {
    width: 640,
    alignSelf: "center",
    cursor: "pointer",
  },
});

export default styles;
