import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: { padding: 16 },
  identityCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0f1a2a",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(246,192,106,0.18)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 6,
  },
  avatar: { width: 64, height: 64, borderRadius: 10, marginRight: 12 },
  identityText: { flex: 1 },
  name: { color: "#f8fafc", fontSize: 18, fontWeight: "700" },
  license: { color: "#f6b11c", marginTop: 4 },
  company: { color: "#cbd5e1", marginTop: 2 },
  section: {
    marginTop: 20,
    backgroundColor: "#0b1528",
    padding: 12,
    borderRadius: 12,
  },
  sectionTitle: { color: "#94a3b8", fontWeight: "700", marginBottom: 8 },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
  },
  rowLeft: { flexDirection: "row", alignItems: "center" },
  rowLabel: { color: "#f8fafc", fontWeight: "600" },
  rowSub: { color: "#94a3b8", fontSize: 12 },
  navRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 6,
    borderRadius: 10,
    marginTop: 8,
    backgroundColor: "#071428",
  },
  navLabel: { color: "#f8fafc", fontWeight: "600" },
  logoutBtn: {
    marginTop: 20,
    backgroundColor: "#ef7c54",
    padding: 12,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#ef7c54",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 4,
  },
  logoutText: { color: "#071122", fontWeight: "800" },
  editBtn: {
    backgroundColor: "#0ea5a4",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  editText: { color: "#071122", fontWeight: "800" },
  saveBtn: {
    backgroundColor: "#f59e0b",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  saveText: { color: "#071122", fontWeight: "900" },
  cancelBtn: {
    backgroundColor: "#334155",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
  },
  cancelText: { color: "#f8fafc", fontWeight: "700" },
  input: {
    color: "#f8fafc",
    fontSize: 16,
    fontWeight: "700",
    borderBottomWidth: 0,
    paddingVertical: 4,
  },
  smallInput: {
    color: "#cbd5e1",
    fontSize: 14,
    paddingVertical: 4,
    borderBottomWidth: 0,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
  },
  infoLabel: { color: "#94a3b8", fontSize: 13, fontWeight: "700" },
  infoValue: { color: "#f8fafc", fontSize: 14, fontWeight: "700" },
});

export default styles;
