import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  brandMark: {
    width: 30,
    height: 30,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  brandDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: "#f6c06a",
  },
  brandText: {
    color: "#f6c06a",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 1.2,
    fontFamily: Platform.select({ ios: "Avenir Next Condensed", android: "sans-serif-condensed", default: undefined }),
  },
  brandSubtext: {
    color: "#bac7e7",
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 2.2,
    marginTop: 1,
  },
  signalGlyph: {
    width: 18,
    height: 18,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "#f6c06a",
    borderTopColor: "transparent",
    borderLeftColor: "transparent",
    transform: [{ rotate: "45deg" }],
  },
  connectionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  connectionDot: {
    width: 14,
    height: 14,
    borderRadius: 999,
    backgroundColor: "#5be4b4",
    shadowColor: "#5be4b4",
    shadowOpacity: 0.5,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
    elevation: 5,
  },
  sectionPanel: {
    borderWidth: 1,
    borderColor: "rgba(246, 192, 106, 0.35)",
    backgroundColor: "rgba(16, 24, 44, 0.88)",
    padding: 14,
    gap: 14,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionHeaderLeft: {
    color: "#ecf0ff",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 1,
  },
  sectionHeaderRight: {
    color: "#f0c88f",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 1.1,
  },
  statusBannerBase: {
    minHeight: 156,
    flexDirection: "row",
    overflow: "hidden",
  },
  statusBannerWaiting: {
    backgroundColor: "#4a3b28",
  },
  statusBannerSuccess: {
    backgroundColor: "#0f3b2c",
  },
  statusBannerError: {
    backgroundColor: "#3d1f25",
  },
  statusStripeBase: {
    width: 8,
  },
  statusStripeWaiting: {
    backgroundColor: "#f6c06a",
  },
  statusStripeSuccess: {
    backgroundColor: "#10b981",
  },
  statusStripeError: {
    backgroundColor: "#ef4444",
  },
  statusBody: {
    flex: 1,
    paddingHorizontal: 18,
    paddingVertical: 20,
    justifyContent: "center",
  },
  statusKicker: {
    color: "#f5cf92",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.8,
    marginBottom: 12,
  },
  statusHeadlineBase: {
    fontSize: 29,
    fontWeight: "900",
    lineHeight: 37,
    letterSpacing: 0.3,
    fontFamily: Platform.select({ ios: "Avenir Next Condensed", android: "sans-serif-condensed", default: undefined }),
  },
  statusHeadlineWaiting: {
    color: "#f8c883",
  },
  statusHeadlineSuccess: {
    color: "#7df0c6",
  },
  statusHeadlineError: {
    color: "#ff9c9c",
  },
  qrCard: {
    alignItems: "center",
    gap: 16,
  },
  qrFrame: {
    width: 300,
    height: 300,
    padding: 16,
    borderRadius: 20,
    backgroundColor: "#f4ead9",
    borderWidth: 1,
    borderColor: "#f0c88f",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 12 },
    shadowRadius: 20,
    elevation: 8,
  },
  qrImage: {
    width: '100%',
    height: '100%',
    borderRadius: 14,
  },
  qrGrid: {
    flex: 1,
    backgroundColor: "#111318",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 14,
    borderColor: "#f8f3ec",
    position: "relative",
  },
  qrRow: {
    flexDirection: "row",
  },
  qrCell: {
    width: 19,
    height: 19,
    margin: 2,
    backgroundColor: "#f5f7fb",
  },
  qrCellEmpty: {
    backgroundColor: "#151a1f",
  },
  qrCenterDot: {
    position: "absolute",
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: "#e24d3a",
  },
  qrBadge: {
    width: "100%",
    backgroundColor: "#f6c06a",
    paddingVertical: 15,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#111827",
  },
  qrBadgeText: {
    color: "#111827",
    fontSize: 19,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  quickActionsRow: {
    flexDirection: "row",
    gap: 10,
  },
  quickAction: {
    flex: 1,
    minHeight: 52,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  quickActionSuccess: {
    backgroundColor: "rgba(16, 185, 129, 0.16)",
    borderColor: "rgba(16, 185, 129, 0.55)",
  },
  quickActionError: {
    backgroundColor: "rgba(239, 68, 68, 0.16)",
    borderColor: "rgba(239, 68, 68, 0.55)",
  },
  quickActionSuccessText: {
    color: "#86efcd",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  quickActionErrorText: {
    color: "#fecaca",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  errorPanel: {
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.5)",
    backgroundColor: "rgba(61, 31, 37, 0.78)",
    borderRadius: 12,
    padding: 12,
    gap: 6,
  },
  errorTitle: {
    color: "#ffb4b4",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  errorText: {
    color: "#fcd5d5",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "600",
  },
  resetButton: {
    minHeight: 52,
    minWidth: 150,
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 0,
    backgroundColor: "#f59e0b",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    shadowColor: "#f59e0b",
    shadowOpacity: 0.28,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  resetButtonText: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "800",
    letterSpacing: 0.6,
  },
  hintPanel: {
    borderWidth: 1,
    borderColor: "rgba(246, 192, 106, 0.25)",
    backgroundColor: "rgba(16, 24, 44, 0.66)",
    borderRadius: 12,
    padding: 12,
    gap: 5,
  },
  hintTitle: {
    color: "#dbe3fb",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  hintText: {
    color: "#bfc8df",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "600",
  },
  footerSpacer: {
    height: 12,
  },
  qrModalOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "rgba(2,6,23,0.8)",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  qrModalInner: {
    width: "100%",
    maxWidth: 420,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "transparent",
  },
  qrModalFrame: {
    width: "100%",
    backgroundColor: "#f4ead9",
    padding: 18,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#f0c88f",
    alignItems: "center",
    justifyContent: "center",
  },
  largeQrImage: {
    width: 320,
    height: 320,
    borderRadius: 16,
  },
  qrModalActions: {
    marginTop: 16,
    alignItems: "center",
    gap: 14,
    paddingBottom: 8,
  },
});

export default styles;
